// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDa5uoQ6dn41ytcT2jEdHOm6v-E_3snr_c',
    appId: '1:332358911795:web:0af593b03fe12912cde046',
    messagingSenderId: '332358911795',
    projectId: 'ecommerce-storage-api',
    authDomain: 'ecommerce-storage-api.firebaseapp.com',
    storageBucket: 'ecommerce-storage-api.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSBuCLR1ktXYbOBZqRbW-AJW2VIW1xvm8',
    appId: '1:332358911795:android:7f7ffc5a6a14ece5cde046',
    messagingSenderId: '332358911795',
    projectId: 'ecommerce-storage-api',
    storageBucket: 'ecommerce-storage-api.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCruo-FDAa1JjaU0hokCuRKWCbxPEYNvwE',
    appId: '1:332358911795:ios:65b2a90fd4bc467ccde046',
    messagingSenderId: '332358911795',
    projectId: 'ecommerce-storage-api',
    storageBucket: 'ecommerce-storage-api.appspot.com',
    iosBundleId: 'fr.imnibis.EcommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCruo-FDAa1JjaU0hokCuRKWCbxPEYNvwE',
    appId: '1:332358911795:ios:7073bb347adc543acde046',
    messagingSenderId: '332358911795',
    projectId: 'ecommerce-storage-api',
    storageBucket: 'ecommerce-storage-api.appspot.com',
    iosBundleId: 'com.example.ecommerceApp.RunnerTests',
  );
}
